# Generated by Django 5.1.3 on 2024-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstaticdata',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
