# Generated by Django 5.1.3 on 2024-11-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(max_length=255)),
                ('target_variable', models.CharField(max_length=255)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('forecast_csv_path', models.CharField(max_length=255)),
            ],
        ),
    ]
