# Generated by Django 5.1.3 on 2024-11-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_state', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('active', models.IntegerField()),
                ('incident_rate', models.FloatField(blank=True, null=True)),
                ('case_fatality_ratio', models.FloatField(blank=True, null=True)),
                ('file_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vaccinations', models.BigIntegerField()),
                ('persons_vaccinated_first_dose', models.BigIntegerField()),
                ('persons_last_dose', models.BigIntegerField()),
                ('persons_booster_add_dose', models.BigIntegerField()),
                ('first_vaccine_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.country')),
            ],
        ),
    ]
