# Generated by Django 5.1.3 on 2024-11-19 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vaccinations', models.BigIntegerField(default=0)),
                ('persons_vaccinated_first_dose', models.BigIntegerField(default=0)),
                ('persons_last_dose', models.BigIntegerField(default=0)),
                ('persons_booster_add_dose', models.BigIntegerField(default=0)),
                ('first_vaccine_date', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('file_date', models.DateField(blank=True, db_index=True, null=True)),
                ('confirmed', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('incident_rate', models.FloatField(blank=True, null=True)),
                ('case_fatality_ratio', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid_data', to='data_app.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'province_state'], name='data_app_co_country_74e480_idx'), models.Index(fields=['file_date'], name='data_app_co_file_da_b717ec_idx')],
            },
        ),
    ]
