# Generated by Django 5.1.3 on 2024-11-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_alter_country_latitude_alter_country_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinationdata',
            name='persons_booster_add_dose',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinationdata',
            name='persons_last_dose',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinationdata',
            name='persons_vaccinated_first_dose',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinationdata',
            name='total_vaccinations',
            field=models.BigIntegerField(default=0),
        ),
    ]
