# Generated by Django 5.1.3 on 2024-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_alter_coviddata_active_alter_coviddata_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
