# Generated by Django 5.1.3 on 2024-11-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid_data', to='data_app.country'),
        ),
    ]
